# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ccc879719d3544add4c950a799ba9e4cfb4567f3b078aed0bd3d7e3472db4081dfaf0ed3276e1f4cb101877f26ea919353a0f2a236f2314c081e028f0c8a9cb

test:
  secret_key_base: a59841f1246c29ba6a6cb61a6fd4135cbe8d241257d4a4d69896e135102c92dec98804ef2fc2785a464e3b0c9f1678d49c500e560e99174ec1243c1df4483c71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
